<div class="col-md-6 mx-auto mt-4">
            <form action="" method="get">
            <div class="input-group">
                <input name="search" class="form-control border-right-0 border p-2" type="search" placeholder="Part of comment, first name, last name or comment ID" id="search" value="<?=$search?>">
                <span class="input-group-append">
                    <button class="btn btn-outline-primary bg-white border-left-0 border p-2 ms-n3" type="submit">
                        <i class="fa fa-search text-primary"></i>
                    </button>
                </span>
            </div>
            </form>
        </div>