<div class="container m-auto">
    <div class="row m-auto">
        <div class="col-11 col-xl-6 m-auto p-4 bg-info text-center">
            <form action="" method="post">
                <div class="mb-3">
                    <label for="opis" class="form-label">Comment:</label>
                    <textarea name="opis" id="opis" cols="30" rows="10" class="form-control text-center rounded"><?=$info->opis?></textarea>
                </div>
                <h4><?=$message?></h4>
                <div class="mb-3">
                    <a href="<?=App::config('url')?>comments/index" class="btn btn-outline-danger"><i class="me-2 fa fa-x"></i> CANCEL</a>
                    <button type="submit" class="btn btn-outline-success"><i class="me-2 fa fa-check"></i> UPDATE</button>
                </div>
            </form>
        </div>
    </div>
</div>