<div class="container m-auto">
    <div class="col-10 m-auto text-center shadow">
        <form method="post" class="form-control p-4" action="">
        <div class="col-md-6 mx-auto m-4">
            <label for="title">Post title:</label>
            <input class="form-control" type="text" name="title" id="title" value="<?=$info[0]->posttitle?>">
        </div>
        <div class="col-md-6 mx-auto m-4">
            <label for="description">Post description:</label>
            <textarea class="form-control" type="text" name="description" id="description"><?=$info[0]->postdescription?></textarea>
        </div>
        <div>
            <a href="<?=App::config('url')?>post/index/<?=$info[0]->postid?>" class="btn btn-lg d-inline-block btn-danger text-white my-4 mx-2 px-4">CANCEL</a>
        <button class="btn btn-lg d-inline-block btn-primary text-white my-4 mx-2 px-4" type="submit">UPDATE</button>
        </div>
    </form>
    </div>
</div>