<section>
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10 col-xl-8">
        <div class="card p-2">
          <div class="card-body">
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="<?=$info->photo?>" alt="avatar" width="60"
                height="60" />
              <div class="">
                <div class="d-flex">
                <h6 class="fw-bold text-primary m-auto p-2 text-break">
                  <?=$info->posttitle?> 
                </h6>
              </div>
              <p class="small bg-primary text-white p-2 m-auto text-center">by: <?=$info->postauthor?></p>
              <?php if($info->authorid == $_SESSION['auth']->sifra):?>
                        <div class="m-auto text-center">
                        <a href="<?=App::config('url')?>post/edit/<?=$info->postid?>" class="ms-3 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-pen"></i></a>
                        <a onclick="return confirm('Are you sure you want to delete this post?');" href="<?=App::config('url')?>post/delete/<?=$info->postid?>" class="ms-1 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-trash"></i></a>
                        </div>
                        <?php endif;?>
                <p class="text-muted small mb-0">
                  Posted - <?=date('d.m.Y.',strtotime($info->postcreated))?>
                </p>
              </div>
            </div>
                <hr>
            <p class="mt-3 mb-4 pb-2 text-break">
                <?=$info->postdescription?>
              </p>

            <div class="small d-flex justify-content-start">
            <button type="button" class="d-flex align-items-center btn btn-primary text-center" data-bs-toggle="popover" title="Liked by" data-bs-content='<?php foreach($likes as $l) {echo $l->likedby . PHP_EOL;}?>'>
              <p class="small m-1"><i class="fa-solid fa-thumbs-up"></i> <?=$info->totalLikes?></p></button>
              <a href="#" class="d-flex align-items-center">
                <?php if(!$liked): ?>
                <a href="<?=App::config('url')?>like/new/<?=$info->postid?>" class="mb-0 mx-3 btn btn-primary text-white shadow"><i class="far fa-thumbs-up me-2"></i>Like</a>
                <?php else: ?>
                <a href="<?=App::config('url')?>like/delete/<?=$likeid?>" class="mb-0 mx-3 btn btn-primary text-white shadow"><i class="far fa-thumbs-down me-2"></i>unLike</a>
                <?php endif;?>
              </a>
            </div>
          </div>
          <form action="<?=App::config('url')?>post/comment/<?=$info->postid?>" method="post">
          <div id="comment" class="card-footer py-3 border-0 bg-white bg-gradient ">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="
                <?php
                  if(file_exists(BP . 'public' . DIRECTORY_SEPARATOR . 'photos' . DIRECTORY_SEPARATOR . 'userProfilePhotos' . DIRECTORY_SEPARATOR . $_SESSION['auth']->sifra . '.png'))
                  {
                      echo (App::config('url') . 'public/photos/userProfilePhotos/' . $_SESSION['auth']->sifra . '.png');
                  }
                  else
                  {
                      echo (App::config('url') . 'public/photos/userProfilePhotos/unknown.png');
                  }
                ?>
                " alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                <textarea name="NewComment" class="form-control" id="NewComment" rows="4"
                  style="background: #fff;" placeholder="Message"></textarea>
              </div>
            </div>
            <div class="float-end mt-2 pt-1 bg-white bg-gradient">
              <button type="submit" class="btn btn-primary btn-sm shadow">
                Post comment
              </button>
              <a href="<?=App::config('url')?>" type="button" class="btn btn-outline-primary btn-sm shadow">
                Cancel
            </a>
            </div>
          </div>
          </form>
        </div>
        <div class="my-3">
        <?php foreach($comments as $comm): ?>
          <div class="card-footer py-3 border-0 bg-white bg-gradient ">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="<?=$comm->photo?>" alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                  <div class="d-flex">
                      <p class="my-auto"><?=$comm->commenter?></p>
                      <?php if($comm->commenterid == $_SESSION['auth']->sifra):?>
                <a href="<?=App::config('url')?>comment/edit/<?=$comm->commentid?>" class="ms-3 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-pen"></i></a>
                <a onclick="return confirm('Are you sure you want to delete comment ?');" href="<?=App::config('url')?>comment/delete/<?=$comm->commentid?>" class="ms-1 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-trash"></i></a>
                <?php endif; ?>
                </div>
                <div class="form-control p-2" id="textAreaExample" rows="4"
                  style="background: #fff;" placeholder="Message">
                  <h6><?=$comm->commentdescription?></h6>
                </div>
              </div>
            </div>
          </div>
          <?php endforeach; ?>
          </div>
      </div>
    </div>
  </div>
</section>
