<section>
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10 col-xl-8">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="60"
                height="60" />
              <div>
                <div class="d-flex">
                <h6 class="fw-bold text-primary m-auto p-2">
                  <?=$info[0]->posttitle?> 
                </h6>
                <p class="small ms-4 bg-primary text-white p-2 m-auto">by: <?=$info[0]->postauthor?></p>
                </div>
                <p class="text-muted small mb-0">
                  Shared publicly - <?=$info[0]->postcreated?>
                </p>
              </div>
            </div>

            <p class="mt-3 mb-4 pb-2">
                <?=$info[0]->postdescription?>
            </p>

            <div class="small d-flex justify-content-start">
              <a href="#" class="d-flex align-items-center me-3">
                <p class="mb-0 btn btn-primary text-white shadow"><i class="far fa-thumbs-up me-2"></i>Like</p>
              </a>
              <a href="#comment" class="d-flex align-items-center me-3">
                <p class="mb-0 btn btn-primary text-white shadow"><i class="far fa-comment-dots me-2"></i>Comment</p>
              </a>
              <a href="#" class="d-flex align-items-center me-3">
                <p class="mb-0 btn btn-primary text-white shadow"><i class="fas fa-share me-2"></i>Share</p>
              </a>
            </div>
          </div>
          <form action="<?=App::config('url')?>post/comment/<?=$info[0]->postid?>" method="post">
          <div id="comment" class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                <textarea name="NewComment" class="form-control" id="NewComment" rows="4"
                  style="background: #fff;" placeholder="Message"></textarea>
              </div>
            </div>
            <div class="float-end mt-2 pt-1">
              <button type="submit" class="btn btn-primary btn-sm shadow">
                Post comment
              </button>
              <a type="button" class="btn btn-outline-primary btn-sm shadow">
                Cancel
            </a>
            </div>
          </div>
          </form>
        <?php foreach($comments as $comm): ?>
          <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                  <div class="d-flex">
                      <p class="my-auto"><?=$comm->commenter?></p>
                      <?php if($comm->commenterid == $_SESSION['auth']->sifra):?>
                <a href="<?=App::config('url')?>comment/edit/<?=$comm->commentid?>" class="ms-3 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-pen"></i></a>
                <a href="<?=App::config('url')?>comment/delete/<?=$comm->commentid?>" class="ms-1 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-trash"></i></a>
                <?php endif; ?>
                </div>
                <div class="form-control p-2" id="textAreaExample" rows="4"
                  style="background: #fff;" placeholder="Message">
                  <h6><?=$comm->commentdescription?></h6>
                </div>
              </div>
            </div>
          </div>
          <?php endforeach; ?>
        </div>
      </div>
    </div>
  </div>
</section>