<div class="container m-auto">
    <div class="col-10 m-auto text-center shadow">
    <form class="form-control p-4" action="" method="post">
        <div class="col-md-6 mx-auto m-4">
            <label for="title">Post title:</label>
            <input class="form-control" type="text" name="title" id="title">
        </div>
        <div class="col-md-6 mx-auto m-4">
        <label for="description">Post description:</label>
        <textarea class="form-control" type="text" name="description" id="description"></textarea>
        </div>
        <div>
        <a href="<?=App::config('url')?>user/index" class="btn btn-lg d-inline-block btn-danger text-white my-4 mx-2 px-4">CANCEL</a>
        <button class="btn btn-lg d-inline-block btn-primary text-white my-4 mx-2 px-4" type="submit">CREATE</button>
        </div>
        <h4><?=$message?></h4>
    </form>
    </div>
</div>