<div class="container m-auto">
    <div class="col-10 m-auto text-center">
    <form class="form-control p-4" action="" method="post">
        <label for="title">Post title:</label>
        <input class="form-control" type="text" name="title" id="title">
        <label for="description">Post description:</label>
        <textarea class="form-control" type="text" name="description" id="description"></textarea>
        <button class="btn btn-lg d-block btn-primary text-white my-4" type="submit">CREATE</button>
    </form>
    </div>
</div>