<div class="col-10 col-md-6 m-auto">
    <div class="container bg-primary p-4 m-auto">
        <p class="h5 text-white text-center">Post you are looking for has not been found!</p>
    </div>
    <br>
    <div class="container bg-primary p-4 m-auto">
        <p class="h5 text-white text-center">Start again from home page?</p>
        <br>
        <a href="<?=App::config('url')?>" class="btn btn-primary d-block border border-2 border-light">Back to home page</a>
    </div>
</div>