<div class="container">
    <div class="row mt-4">
        <div class="col-12 col-md-9 col-lg-6 m-auto text-center p-4 border border-1 border-primary rounded rounded-3 bg-white bg-gradient shadow">
            <img class="mt-2 rounded-circle border border-3 border-primary" src="https://picsum.photos/400?random=<?=$e->sifra?>" alt="" height="100" width="100">
            <h3><?=$e->ime?> <?=$e->prezime?></h3>
            <?php if(!($e->brojtel=='' || $e->brojtel<=0)): ?>
                <h5 class="d-inline-flex"><i class="d-inline-flex me-3 fa-solid fa-phone"></i> <?=$e->brojtel?></h5>
                <br>
                <?php endif; ?>
                <h5 class="d-inline-block text-break"><i class="d-inline-flex me-3 fa-solid fa-envelope"></i> <?=$e->email?></h5>
                <br>
                <h5><i class="d-inline-block me-3 fa-solid fa-cake-candles"></i> <?=$e->datumrodenja?></h5>
                <br>
                <div class="d-inline-flex mx-4">
                    <p class="px-2">ACTIVE: <i class="fa fa-solid fa-<?=$e->stanje?>"></i></p>
                    <p class="px-2">ADMIN: <i class="fa fa-solid fa-<?=$e->administrator?>"></i></p>
                </div>
                <div class="col-auto">
                    <form action="" method="post">
                    <label for="inputPassword6" class="col-form-label">New password</label>
                    <input name="password" type="password" id="inputPassword6" class="form-control rounded rounded-2 mx-auto w-75 " aria-describedby="passwordHelpInline">
                    <div class="auth__form_actions pb-4 m-3 d-inline-flex">
                        <a href="<?=App::config('url')?>users/index" class="m-2 btn btn-danger btn-lg btn-block rounded rounded-pill">
                            <i class="text-white me-2 fa-solid fa-x"></i>CANCEL
                        </a>
                        <button type="submit" class="m-2 btn btn-primary btn-lg btn-block rounded rounded-pill">
                            <i class="text-white me-2 fa-solid fa-check"></i>UPDATE
                        </button>
                        </div>
                    </div>
                </div>
                <div class="text-danger pt-2 text-center h5 text-uppercase">
                    <span><?=$message?></span>
                </div>
                </form>
            </div>
        </div>