
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-12">
            <a href="<?=App::config('url')?>users/new" class="bg-success btn btn-lg d-grid">Add new user</a>
            <table class="table table-dark">
    <thead class="text-center font-weight-bold">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Phone</th>
            <th>E-mail</th>
            <th>DOB</th>
            <th>Active</th>
            <th>Administrator</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody class="text-center">
        <?php foreach($info as $red): ?>
            <tr>
                <td><?=$red->sifra?></td>
                <td><?=$red->ime?> <?=$red->prezime?></td>
                <td><?=$red->brojtel?></td>
                <td><?=$red->email?></td>
                <td><?=$red->datumrodenja?></td>
                <td><i class="fa fa-solid fa-<?=$red->stanje?>"></i></td>
                <td><i class="fa fa-solid fa-<?=$red->administrator?>"></i></td>
                <td>
                <a href="update/<?=$red->sifra?>"><i class="fa fa-pencil"></i></a>    
                <a href="delete/<?=$red->sifra?>"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
        </div>
    </div>
</div>
