<?php if(!isset($email)) {$email='';}?>
<link rel="stylesheet" href="<?=App::config('url')?>public/css/login.css">
<div class="container">
    <div class="auth">
  <div class="auth__body">
    <form action="<?=App::config('url')?>users/new" class="auth__form" autocomplete="off" method="POST">
      <div class="auth__form_body">
        <div>
            <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
        <div class="form-group">
            <label for="fname" class="text-uppercase small">First name :</label>
            <input name="fname" id="fname" type="text" class="form-control" placeholder="John">
          </div>
          <div class="form-group">
            <label for="lname" class="text-uppercase small">Last Name :</label>
            <input name="lname" id="lname" type="text" class="form-control" placeholder="Doe">
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
        <div class="form-group">
          <label for="dob" class="text-uppercase small">Date of birth :</label>
          <input name="dob" id="dob" type="date" class="form-control">
        </div>
        <div class="form-group">
          <label for="email" class="text-uppercase small">Email :</label>
          <input name="email" id="email" type="email" class="form-control" placeholder="john@doe.com" value="<?=$e->  email?>">
        </div>
        </div>
          <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
          <div class="form-group">
            <label for="password" class="text-uppercase small">Password :</label>
            <input name="password" id="password" type="password" placeholder="*****" class="form-control">
          </div>
          <div class="form-group">
            <label for="confirmpw" class="text-uppercase small">Confirm password :</label>
            <input name="confirmpw" id="confirmpw" type="password" placeholder="*****" class="form-control">
          </div>
          </div>
        </div>
        </div>
    </div>
    <div class="text-danger pt-2 text-center h5 text-uppercase">
      <span><?=$message?></span>
    </div>
      <div class="auth__form_actions">
        <a href="<?=App::config('url')?>users/index" id="logintext" class="mx-2 btn btn-danger btn-lg btn-block">
        <i id="fingerprinticon" class="fa-solid fa-x"></i>CANCEL
        </a>
        <button type="submit" id="logintext" class="mx-2 btn btn-primary btn-lg btn-block">
        <i id="fingerprinticon" class="fa-solid fa-pencil"></i>CREATE
        </button>
        <div class="mt-2" id="fgtpw">
        </div>
      </div>
    </form>
  </div>
</div>
    </div>