<?php
if(!isset($e->datumrodenja)){$e->datumrodenja=$e->dob;}
if(!isset($e->ime)) {$e->ime=$e->fname;}
if(!isset($e->prezime)) {$e->prezime=$e->lname;}
if(!isset($e->lozinka)) {$e->lozinka=$e->password;}
if(!isset($e->stanje)) {$e->stanje=$e->status;}
if(!isset($e->administrator)) {$e->administrator=$e->admin;}
if(!isset($e->phnum)) {$e->phnum='';}
if(!isset($e->brojtel)) {$e->brojtel=$e->phnum;}
?>
<div class="container">
    <div class="auth">
  <div class="auth__body">
    <form autocomplete="off" action="" class="auth__form" autocomplete="off" method="POST">
      <div class="auth__form_body">
        <div>
            <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
        <div class="form-group">
            <label for="fname" class="text-uppercase small">First name :</label>
            <input name="fname" id="fname" type="text" class="form-control" placeholder="John" value="<?=$e->ime?>">
          </div>
          <div class="form-group">
            <label for="lname" class="text-uppercase small">Last Name :</label>
            <input name="lname" id="lname" type="text" class="form-control" placeholder="Doe" value="<?=$e->prezime?>">
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
        <div class="form-group">
          <label for="dob" class="text-uppercase small">Date of birth :</label>
          <input name="dob" id="dob" type="date" class="form-control" value="<?=$e->datumrodenja?>">
        </div>
        <div class="form-group">
          <label for="email" class="text-uppercase small">Email :</label>
          <input name="email" id="email" type="email" class="form-control" placeholder="john@doe.com" value="<?=$e->email?>">
        </div>
        <div class="form-group">
          <label for="phnum" class="text-uppercase small">Phone number :</label>
          <input name="phnum" id="phnum" type="tel" class="form-control" placeholder="+385 XXXXXXX" value="<?=$e->brojtel?>">
        </div>
        </div>
          <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 text-center">
          <div class="form-group">
            <a href="<?=App::config('url')?>users/changepassword/<?=$e->sifra?>" class="btn btn-lg btn-primary mt-2 mb-2 col-12">CHANGE PASSWORD</a>
          </div>
          <div class="form-group">
            <div class="form-control text-center">
              <p>Active</p>
              <input type="radio" name="status" id="yes" value="true"
              <?php if($e->stanje): ?>
              checked="checked">
              <?php endif; ?>
              <label for="yes">YES</label>
              <input type="radio" name="status" id="no" value="false"
              <?php if(!$e->stanje): ?>
              checked="checked">
              <?php endif; ?>
              <label for="no">NO</label>
            </div>
            <div class="form-control text-center">
              <p>Admin</p>
              <input type="radio" name="admin" id="yes" value="true"
              <?php if($e->administrator): ?>
              checked="checked">
              <?php endif; ?>
              <label for="yes">YES</label>
              <input type="radio" name="admin" id="no" value="false"
              <?php if(!$e->administrator): ?>
              checked="checked">
              <?php endif; ?>
              <label for="no">NO</label>
            </div>
          </div>
          </div>
        </div>
        </div>
    </div>
    <div class="text-danger mt-4 text-center h5 text-uppercase">
      <span><?=$message?></span>
    </div>
      <div class="auth__form_actions pb-4">
      <a href="<?=App::config('url')?>users/index" id="logintext" class="btn btn-danger btn-lg btn-block">
        <i id="fingerprinticon" class="fa-solid fa-x"></i>CANCEL
            </a>
        <button type="submit" id="logintext" class="btn btn-primary btn-lg btn-block">
        <i id="fingerprinticon" class="fa-solid fa-check"></i>UPDATE
        </button>
        <div class="mt-2" id="fgtpw">
        </div>
      </div>
    </form>
  </div>
</div>
    </div>