<div class="container m-auto">
    <div class="col-11 col-lg-7 m-auto">
        <form action="" method="post" class="text-center bg-info p-4 rounded">
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input name="password" type="password" class="form-control text-center rounded-pill" id="password" placeholder="••••••••" value="<?=$info->password?>" autocomplete="new-password">
            </div>
            <div class="mb-3">
                <label for="confirmpw" class="form-label">Confirm password</label>
                <input name="confirmpw" type="password" class="form-control text-center rounded-pill" id="confirmpw" placeholder="••••••••" value="<?=$info->confirmpw?>">
            </div>
            <h4 class="text-danger"><?=$message?></h4>
            <div class="mb-3">
                <a href="<?=App::config('url')?>operater/index" class="btn btn-danger"><i class="me-2 fa fa-x"></i> CANCEL</a>
                <button type="submit" class="btn btn-primary"><i class="me-2 fa fa-check"></i> UPDATE</button>
            </div>
        </form>
    </div>
</div>