<div class="container m-auto">
    <div class="col-11 col-lg-7 m-auto">
        <form action="" method="post" class="text-center bg-info p-4 rounded">
            <div class="mb-3">
                <label for="fname" class="form-label">First name</label>
                <input name="fname" type="text" class="form-control text-center rounded-pill" id="fname" placeholder="John" value="<?=$info->fname?>">
            </div>
            <div class="mb-3">
                <label for="lname" class="form-label">Last name</label>
                <input name="lname" type="text" class="form-control text-center rounded-pill" id="lname" placeholder="Doe" value="<?=$info->lname?>">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email address</label>
                <input name="email" type="email" class="form-control text-center rounded-pill" id="email" placeholder="john@doe.com" value="<?=$info->email?>">
            </div>
            <div class="mb-3">
                <a class="btn btn-primary d-block" href="<?=App::config('url')?>operater/changePassword/<?=$info->sifra?>">CHANGE PASSWORD</a>
            </div>
            <h4 class="text-danger"><?=$message?></h4>
            <div class="mb-3">
                <a href="<?=App::config('url')?>operater/index" class="btn btn-danger"><i class="me-2 fa fa-x"></i> CANCEL</a>
                <button type="submit" class="btn btn-primary"><i class="me-2 fa fa-check"></i> SAVE</button>
            </div>
        </form>
    </div>
</div>