<a href="new">Add new operater</a>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>E-mail</th>
            <th>Uloga</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($info as $i):?>
            <tr>
                <td><?=$i->ime?> <?=$i->prezime?></td>
                <td><?=$i->email?></td>
                <td><?=$i->uloga?></td>
                <td>
                    <a href="change?id=<?=$i->sifra?>">Change</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>