<div class="container">
    <div class="row mt-3">
        <div class="col-11">
            <ul>
                <div>
                    <a href="<?=App::config('url')?>operater/new" class="btn btn-success d-block">ADD NEW OPERATER</a>
                </div>
            <?php foreach($info as $i): ?>
                <div class="text-center">
                <p class="bg-info text-dark rounded-pill my-1 p-3">Name: <?=$i->ime?> <?=$i->prezime?> | E-mail: <?=$i->email?> <a class="btn btn-primary ms-3" href="<?=App::config('url')?>operater/edit/<?=$i->sifra?>"><i class="fa fa-pen"></i></a><a class="btn btn-primary ms-3" onclick="return confirm('Are you sure you want to delete this operater?');" href="<?=App::config('url')?>operater/delete/<?=$i->sifra?>"><i class="fa fa-trash"></i></a></p>
                </div>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
