<div class="container m-auto">
    <div class="col-11 col-lg-6 m-auto">
        <form action="" method="post" class="text-center p-4 bg-info rounded">
            <div class="mb-3">
                <label for="password" class="form-label">New password</label>
                <input name="password" type="password" class="form-control text-center px-3 rounded-pill" value="<?=$info->password?>">
            </div>
            <div class="mb-3">
                <label for="confirmpw" class="form-label">Confirm new password</label>
                <input name="confirmpw" type="password" class="form-control text-center px-3 rounded-pill" value="<?=$info->confirmpw?>">
            </div>
            <h4 class="text-danger"><?=$message?></h4>
            <div class="mb-3">
                <a href="" class="btn btn-danger"><i class="me-2 fa fa-x"></i> CANCEL</a>
                <button class="btn btn-primary"><i class="me-2 fa fa-check"></i> UPDATE</button>
            </div>
        </form>
    </div>
</div>