<div class="container m-auto">
    <div class="col-11 col-lg-6 m-auto">
        <form action="" method="post" class="p-4 text-center bg-info">
            <div class="mb-3">
                <label for="fname" class="form-label">First name</label>
                <input type="text" class="form-control text-center rounded-pill" name="fname" value="<?=$info->fname?>">
            </div>
            <div class="mb-3">
                <label for="lname" class="form-label">Last name</label>
                <input type="text" class="form-control text-center rounded-pill" name="lname" value="<?=$info->lname?>">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">E-mail address</label>
                <input type="email" class="form-control text-center rounded-pill" name="email" value="<?=$info->email?>">
            </div>
            <div class="mb-3">
                <a href="<?=App::config('url')?>user/changePassword/<?=$_SESSION['auth']->sifra?>" class="btn btn-primary d-block">Change password</a>
            </div>
            <h4><?=$message?></h4>
            <div class="mb-3">
                <a href="<?=App::config('url')?>user/myProfile" class="btn btn-danger"><i class="me-2 fa fa-x"></i> CANCEL</a>
                <button class="btn btn-primary"><i class="me-2 fa fa-check"></i> UPDATE</button>
            </div>
        </form>
    </div>
</div>