<!--BEGIN FEED-->
<section>
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10 col-xl-8">
        <div class="card bg-info">
          <div class="card-body p-4 rounded-3">
            <h4 class="text-center mb-4 pb-2 fw-bolder text-dark">YOUR FEED</h4>

            <div class="row">
              <div class="col">
                <a href="<?=App::config('url')?>post/new" class="btn btn-lg d-block btn-primary text-white shadow">ADD NEW POST</a>
                <?php include 'pagination.phtml';?>
              <!-- POST TEMPLATE BEGIN -->
              <?php foreach($info as $row): ?>
              <div class="d-flex flex-top my-3 border border-1 border-primary px-2 py-4 rounded rounded-3 shadow bg-white">
                <div>
                  <img class="d-flexbox rounded-circle shadow-1-strong mx-2 text-center shadow"
                    src="<?=$row->photo?>" alt="<?=$row->postauthor?>" width="65"
                    height="65" />
                    <br>
                    <div class="text-center my-2">
                    <?php if($row->authorid == $_SESSION['auth']->sifra):?>
                    <a href="<?=App::config('url')?>post/edit/<?=$row->postid?>" class="d-inline-flex p-2 me-1 btn btn-square btn-primary text-white text-center shadow"><i class="fa-solid fa-pen"></i></a>
                    <a onclick="return confirm('Are you sure you want to delete this post?');" href="<?=App::config('url')?>post/delete/<?=$row->postid?>" class="d-inline-flex p-2 btn btn-square btn-primary text-white shadow"><i class="fa-solid fa-trash"></i></a>
                    <?php endif;?>
                    </div>
                  </div>
                  <div class="flex-grow-1 flex-shrink-1">
                    <div>
                        <p class="mb-1 text-center text-break px-4 h4">
                         <?=$row->posttitle?>
                        </p>
                      <p class="small mb-0 text-center text-break px-4">
                        <?=$row->postdescription?>
                      </p>
                      <!-- <p class="small m-1 btn btn-primary"><i class="fa-solid fa-thumbs-up"></i> <?=$row->totalLikes?></p> -->
                    </div>
                    <div class="d-flexbox text-center m-1">
                      <p class="text-nowrap col-3 small d-inline me-3 bg-primary p-2 text-white"><i class="fa-solid fa-thumbs-up"></i> <?=$row->totalLikes?></p>
                      <a href="<?=App::config('url')?>post/index/<?=$row->postid?>" class="p-1 col-8 btn btn-primary shadow">VIEW POST</a>
                    </div>
                      </div>
                      </div>
                      <?php endforeach; ?>
                      <?php include 'pagination.phtml';?>
                <!-- POST TEMPLATE END -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--END FEED-->