<!--BEGIN FEED-->
<section>
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10 col-xl-8">
        <div class="card" id="newscard">
          <div class="card-body p-4">
            <h4 id="newstext" class="text-center mb-4 pb-2">YOUR FEED</h4>

            <div class="row">
              <div class="col">
                <a href="<?=App::config('url')?>post/new" class="btn btn-lg d-block btn-primary text-white">ADD NEW POST</a>
                
              <!-- POST TEMPLATE BEGIN -->
              <?php foreach($info as $row): ?>
              <div class="d-flex flex-start my-3 border border-1 border-primary p-4 rounded rounded-3 shadow bg-light">
                <div>
                  <img class="d-flexbox rounded-circle shadow-1-strong mx-4 text-center"
                    src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(10).webp" alt="<?=$row->postauthor?>" width="65"
                    height="65" />
                </div>
                  <div class="flex-grow-1 flex-shrink-1">
                    <div>
                      <div class="d-flex justify-content-between align-items-center">
                        <p class="mb-1 d-inline-block align-text-center h4">
                         <?=$row->posttitle?>
                         <?php if($row->authorid == $_SESSION['auth']->sifra):?>
                          <a href="<?=App::config('url')?>post/edit/<?=$row->postid?>" class="ms-3 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-pen"></i></a>
                          <a onclick="return confirm('Are you sure you want to delete this post?');" href="<?=App::config('url')?>post/delete/<?=$row->postid?>" class="ms-1 btn btn-square btn-primary text-white m-1"><i class="fa-solid fa-trash"></i></a>
                          <?php endif;?>
                        </p>
                      </div>
                      <p class="small mb-0">
                        <?=$row->postdescription?>
                      </p>
                      <p class="small m-1"><i class="fa-solid fa-thumbs-up"></i> <?=$row->totalLikes?></p>
                    </div>
                    <div class="d-grid m-2">
                      <a href="<?=App::config('url')?>post/index/<?=$row->postid?>" class="btn btn-primary shadow">VIEW POST</a>
                    </div>
                      </div>
                      </div>
                      <?php endforeach; ?>
                <!-- POST TEMPLATE END -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--END FEED-->