<nav class="col-12 mx-auto pt-4" aria-label="...">
          <ul class="justify-content-center pagination">
            <!-- PREVIOUS BUTTON -->
            <li class="page-item
            <?php if(($page<=1) || $lastPage==0): ?>
            disabled
            <?php endif; ?>
            ">
              <a class="page-link" href="<?=App::config('url')?>user/index/<?=$page-1?>"
              <?php if(($page<=1) || $lastPage==0): ?>
                tabindex="-1"
              aria-disabled="true"
              <?php endif; ?>
              >Previous</a>
            </li>
            <!-- END PREVIOUS BUTTON -->

        
            <li class="page-item active"><a class="page-link" href="<?=App::config('url')?>user/index/<?=$page?>"><?=$page?></a></li>

            
            <!-- NEXT BUTTON -->
            <li class="page-item
            <?php if(($page>=$lastPage) || $lastPage==0): ?>
            disabled
            <?php endif; ?>
            ">
              <a class="page-link" href="<?=App::config('url')?>user/index/<?=$page+1?>"
              <?php if(($page>=$lastPage) || $lastPage==0): ?>
                tabindex="-1"
              aria-disabled="true"
              <?php endif; ?>
              >Next</a>
            </li>
            <!-- END NEXT BUTTON -->

          </ul>
        </nav>