<div class="container">
    <div class="row mt-4">
        <div class="col-md-5 col-lg-4 col-xl-4">
            <div class="container border border-1 border-primary rounded-3 shadow-lg mx-auto p-4">
                <div class="col-12 d-inline-flex align-items-center mx-auto">
                    <img src="https://picsum.photos/80/80"
                    alt="profilePhoto" height="80px" width="80px" class="rounded-circle shadow">
                    <h4 class="ms-4"><?=$info->ime?> <?=$info->prezime?></h4>
                </div>
                <hr class="text-primary">
                <div class="col-12 align-items-center mx-auto d-inline mx-auto">
                <p class="text-break"><i class="fa-solid fa-envelope text-break"></i>: <?=$info->email?></p>
                </div>
            </div>
        </div>
        <div class="col-md-7 col-lg-8 col-xl-8">

        </div>
    </div>
</div>