<div class="container">
    <div class="row mt-4">
        <div class="col-md-6 col-lg-4 col-xl-4">
            <div class="container border border-1 border-primary rounded-3 shadow-lg mx-auto text-center p-4 my-3 bg-info">
                <div class="col-12 d-inline-flex justify-content-center">
                   <!-- Button trigger modal -->
                   <div title="Click to change profile photo" style="cursor:pointer;">
                     <img src="<?=$info->profilePhoto?>?<?=time()?>" alt="" class="profilePhoto rounded-circle shadow" id="user_<?=$info->sifra?>" style="max-height:100px; max-width:100px" />
                   </div>
                  <?php if($info->sifra==$_SESSION['auth']->sifra): ?>
                  <!-- Modal -->
                  <div class="modal fade" id="profilePhotoModal" tabindex="-1" aria-labelledby="profilePhotoModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="profilePhotoModalLabel">Change profile photo</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body m-auto my-4" style="max-width:500px;max-height:250px">
                          <img id="image" src="" alt="" />
                        </div>
                        <div class="modal-footer">
                          <div class="d-block col-12">
                            <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
                          </div>
                          <button type="button" class="close-button btn btn-secondary" data-bs-dismiss="modal">Close</button>
                          <a href="#" id="savePhoto" class="btn btn-primary">Save changes</a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <?php endif; ?>
                    <h4 class="ms-4 my-auto"><?=$info->ime?> <?=$info->prezime?>
                    <?php if($info->sifra==$_SESSION['auth']->sifra): ?>
                <a class="btn btn-primary ms-1 border border-1 border-primary p-2 shadow" href="<?=App::config('url')?>me/changeName/<?=$info->sifra?>"><i class="fa-solid fa-pen text-break"></i></a>
                <?php endif; ?>
            </h4>
                </div>
                <hr class="text-primary">
                <?php if($info->administrator): ?>
                  <p class="btn bg-warning" style="cursor:default;"><i class="me-2 fa fa-star"></i> ADMINISTRATOR</p>
                <?php endif; ?>
                <div class="col-12 align-items-center mx-auto d-inline">
                <p class="text-break"><i class="fa-solid fa-envelope text-break"></i>: <?=$info->email?>
                <?php if($info->sifra==$_SESSION['auth']->sifra): ?>
                <a class="btn btn-primary ms-1 p-1 shadow" href="<?=App::config('url')?>me/changeEmail/<?=$info->sifra?>"><i class="fa-solid fa-pen text-break"></i></a>
                <?php endif; ?>
            </p>
                </div>
                <div class="col-12 align-items-center mx-auto d-inline">
                <p class="text-break"><i class="fa-solid fa-cake text-break"></i>: <?=date('d.m.Y',strtotime($info->datumrodenja))?>
            <?php if($info->sifra==$_SESSION['auth']->sifra): ?>
                <a class="btn btn-primary ms-1 p-1 shadow" href="<?=App::config('url')?>me/changeDob/<?=$info->sifra?>"><i class="fa-solid fa-pen text-break"></i></a>
            </p>
                <?php endif; ?>
                </div>
                <div class="col-12 align-items-center mx-auto d-inline">
                <?php if(isset($info->brojtel) & $info->brojtel!=null): ?>
                <p class="text-break"><i class="fa-solid fa-phone text-break"></i>: <?=$info->brojtel?>
                <?php if($info->sifra==$_SESSION['auth']->sifra): ?>
                <a class="btn btn-primary ms-1 p-1 shadow" href="<?=App::config('url')?>me/changePhoneNumber/<?=$info->sifra?>"><i class="fa-solid fa-pen text-break"></i></a>
                <a class="btn btn-primary ms-1 p-1 shadow" href="<?=App::config('url')?>me/removePhoneNumber/<?=$info->sifra?>"><i class="fa-solid fa-trash text-break"></i></a></p>
                <?php endif; ?>
                <?php elseif(!isset($info->brojtel) && $info->brojtel==null && $info->sifra==$_SESSION['auth']->sifra): ?>
                    <div class="col-12 align-items-center mx-auto d-inline">
                        <p class="text-break"> <a href="<?=App::config('url')?>me/addPhoneNumber/<?=$info->sifra?>" class="btn btn-primary"><i class="fa-solid fa-phone text-break"></i> ADD PHONE NUMBER</a> </p>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-8 col-xl-8">
        <form class="d-flex flex-grow-1" method="post" action="">
                    <input name="searchpostofusers" id="searchpostofusers" class="form-control me-2 border border-1 border-primary shadow bg-white" type="search" placeholder="Search for posts (post titles)" aria-label="Search for posts (post titles)">
                    <button class="btn btn-outline-primary rounded-circle m-1 shadow" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
        <?php foreach($posts as $row): ?>
              <div class="d-flex flex-top my-3 border border-1 border-primary px-2 py-4 rounded rounded-3 shadow bg-white">
                <div>
                    <img src="<?=$info->profilePhoto?>?<?=time()?>" alt="" class="profilePhoto d-flexbox rounded-circle shadow-1-strong mx-3 text-center shadow border border-2 border-primary" id="user_<?=$info->sifra?>" style="height:50px;width:50px;"/>
                    <br>
                    <div class="text-center my-2">
                    <?php if($row->authorid == $_SESSION['auth']->sifra):?>
                    <a href="<?=App::config('url')?>post/edit/<?=$row->postid?>" class="d-inline-flex p-2 me-1 btn btn-square btn-primary text-white text-center shadow"><i class="fa-solid fa-pen"></i></a>
                    <a onclick="return confirm('Are you sure you want to delete this post?');" href="<?=App::config('url')?>post/delete/<?=$row->postid?>" class="d-inline-flex p-2 btn btn-square btn-primary text-white shadow"><i class="fa-solid fa-trash"></i></a>
                    <?php endif;?>
                    </div>
                  </div>
                  <div class="flex-grow-1 flex-shrink-1">
                    <div>
                        <p class="mb-1 text-center text-break px-4 h4">
                         <?=$row->posttitle?>
                        </p>
                      <p class="small mb-0 text-center text-break px-4">
                        <?=$row->postdescription?>
                      </p>
                      <!-- <p class="small m-1 btn btn-primary"><i class="fa-solid fa-thumbs-up"></i> <?=$row->totalLikes?></p> -->
                    </div>
                    <div class="d-flexbox text-center m-2">
                      <p class="text-nowrap col-3 small d-inline me-3 bg-primary p-2 text-white"><i class="fa-solid fa-thumbs-up"></i> <?=$row->totalLikes?></p>
                      <a href="<?=App::config('url')?>post/index/<?=$row->postid?>" class="p-1 col-8 btn btn-primary shadow">VIEW POST</a>
                    </div>
                      </div>
                      </div>
                      <?php endforeach; ?>
                      <?php include 'paginationForProfile.phtml'?>
        </div>
    </div>
</div>