<div class="m-auto text-center bg-info p-4 rounded-3 shadow">
    <p class="text-white display-1" style="text-shadow: 3px 3px 5px #000000;">404</p>
    <p class="text-white h5" style="text-shadow: 3px 3px 5px #000000;">The page you are looking for does not exist or has been moved to another location!</p>
    <p class="text-white h5" style="text-shadow: 3px 3px 5px #000000;">Start again from home page?</p>
    <a href="<?=App::config('url')?>" class="btn d-block btn-primary shadow mt-4">Back to home</a>
</div>