<div class="container my-auto">
    <div class="row">
        <?php if(!App::auth()):?>
        <div class="col-md-1 col-lg-4 col-xl-4">

        </div>
        <div class="shadow rounded col-12 col-sm-12 col-md-10 col-lg-4 col-xl-4 bg-primary bg-gradient">
            <form method="post" class="form rounded bg-primary text-white p-4 m-2 text-center pt-4 bg-gradient">
            <img class="shadow rounded-circle border bg-gradient border-white p-2 m-2 mx-auto d-block" src="<?=App::config('url')?>public/components/icons/png.png" alt="" height="90px">
            <h5 class="mt-4 mb-4">Before you continue,<br> you need to login or register!</h5>
            <a href="index/login" class="shadow d-grid btn mx-auto px-5 my-2 rounded border-rounded btn-light bg-gradient btn-outline-success">Login</a>
            <a href="index/register" class="shadow d-grid btn mx-auto px-5 my-2 rounded border-rounded btn-light bg-gradient btn-outline-success">Register</a>
        </form>
        </div>
        <div class="col-md-1 col-lg-4 col-xl-4">

        </div>
        <?php else:?>
            <div class="col-md-1 col-lg-4 col-xl-4">

        </div>
        <div class="col-12 col-sm-12 col-md-10 col-lg-4 col-xl-4 bg-primary bg-gradient">
            
        </div>
        <div class="col-md-1 col-lg-4 col-xl-4">

        </div>
        <?php endif;?>
    </div>
</div>