<?php $email = isset($_POST['email']) ? $_POST['email'] : (isset($_COOKIE['email']) ? $_COOKIE['email'] : '');
if(!isset($_POST['email'])){$_POST['email']='';}
 ?>
<div class="container">
    <div class="auth">
  <div class="auth__header">
    <div class="auth__logo">
      <a href="<?=App::config('url')?>"><img height="90" src="<?=App::config('url')?>public/components/icons/png.png" alt=""></a>
    </div>
  </div>
  <div class="auth__body">
    <form action="<?=App::config('url');?>login/authorisation" class="auth__form" autocomplete="off" method="POST">
      <div class="auth__form_body">
        <h3 class="auth__form_title">Sign in</h3>
        <div>
          <div class="form-group">
            <label for="email" class="text-uppercase small">Email :</label>
            <input name="email" id="email" type="email" class="form-control" placeholder="Enter email" value="<?=$_POST['email']?>">
          </div>
          <div class="form-group">
            <label for="password" class="text-uppercase small">Password :</label>
            <input name="password" id="password" type="password" class="form-control" placeholder="Password">
          </div>
        </div>
    </div>
    <div class="text-danger pt-2 text-center h5 text-uppercase">
      <span><?=$message?></span>
    </div>
    <h6 class="text-center">E-mail: oper@edunova.hr <br> Password: edunova</h6>
      <div class="auth__form_actions">
        <button id="logintext" class="btn btn-primary btn-lg btn-block">
        <i id="fingerprinticon" class="fa-solid fa-fingerprint"></i>LOGIN
        </button>
        <div class="mt-2" id="fgtpw">
          <a style="text-decoration: none; color:black;" href="#" class="small text-uppercase">
            Forgot password?
          </a>
        </div>
      </div>
    </form>
  </div>
</div>
    </div>