<!DOCTYPE html>
<html lang="en">
<head>
    <?php include_once 'includes/head.phtml'?>
</head>
<body class="d-flex flex-column min-vh-100">
    <?php include_once 'includes/navbar.phtml'?>
    <?=$contents?>
    <?php include_once 'includes/footer.phtml'?>
    <?php include_once 'includes/scripts.phtml'?>
    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl)
})
        </script>
</body>
</html>