
<div class="container mt-4">
    <div class="row">
    <?php include 'searchbar.phtml'?>
    <?php include 'pagination.phtml'?>

<?php foreach($info as $red) : ?>
        <div class="col-md-6 col-lg-4 text-center ">
            <div class="callout p-4 m-2 border border-1 border-primary rounded rounded-6 bg-white bg-gradient shadow">
                <h3 class="text-break">Title: <?=$red->naslovobjave?></h3>
                <hr class="w-75 mx-auto">
                <h5 class="text-break">Description: <?=$red->upisobjave?></h5>
                <div class="d-inline-flex">
                    <h5 class="mx-3">Post ID: <?=$red->sifraobjave?></h5>
                    <h5 class="mx-3">User ID: <?=$red->sifrakorisnika?></h5>
                </div>
                <h5>User: <?=$red->imekorisnika?> <?=$red->prezimekorisnika?></h5>
                <div class="mt-4">
                    <a class="px-2" href="update/<?=$red->sifraobjave?>"><i class="border border-primary border-2 bg-body rounded-circle p-3 fa-solid fa-pencil"></i></a>    
                    <a class="px-2" onclick="return confirm('Are you sure you want to delete post <?=$red->naslovobjave?>?');" href="delete/<?=$red->sifraobjave?>"><i class="border border-primary border-2 bg-body rounded-circle p-3 fa-solid fa-trash"></i></a>
                </div>
            </div>
        </div>
        <?php endforeach ; ?>

        <?php include 'pagination.phtml'?>
    </div>
</div>