<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=App::config('appName');?></title>
<link rel="stylesheet" href="<?=App::config('url')?>public/css/bootstrap.css">
<link rel="stylesheet" href="<?=App::config('url')?>public/css/app.css">
<?php if(isset($css)): ?>
    <link rel="stylesheet" href="<?=App::config('url')?>public/css/<?=$css?>">
<?php endif; ?>
<link rel="shortcut icon" href="<?=App::config('url')?>public/components/icons/png.png" type="image/x-icon">

<?php /* https://css-tricks.com/essential-meta-tags-social-media/ */?>
<!--  Essential META Tags -->
<meta property="og:title" content="<?=App::config('appName');?>">
<meta property="og:type" content="article" />
<meta property="og:image" content="<?=App::config('url')?>public/img/thumbnail.jpg">
<meta property="og:url" content="<?=App::config('url')?>">
<meta name="twitter:card" content="summary_large_image">

<!--  Non-Essential, But Recommended -->
<meta property="og:description" content="<?=App::config('appName');?>">
<meta property="og:site_name" content="<?=App::config('appName');?>">
<meta name="twitter:image:alt" content="<?=App::config('appName');?>">