<!--BEGIN NAVBAR-->
<?php if(App::auth()): ?>
<nav class="navbar navbar-expand-lg navbar-dark bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="<?=App::config('url')?>"><img style="margin-right: 3%;" class="d-inline-block align-text-top rounded rounded-circle border border-1 border-primary p-2 btn btn-primary bg-gradient" src="<?=App::config('url')?>public/components/icons/png.png" height="50" width="50"></a>
    <?php if(!App::admin() && !App::oper()): ?>
    <form class="d-flex flex-grow-1 w-50" method="post" action="">
                    <input name="search" id="search" class="form-control me-2 bg-light border border-1 border-primary shadow" type="search" placeholder="Search for users or posts" aria-label="Search for friends or posts">
                    <button class="btn btn-outline-primary rounded-circle m-1 shadow" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
      <?php endif; ?>
    <button class="navbar-toggler bg-primary bg-gradient shadow rounded-circle m-1 p-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon text-primary shadow"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <?php if(App::admin()): ?>
                        <li class="nav-item shadow btn btn-primary rounded rounded-3 bg-gradient mx-2"><a class="nav-link text-white" href="<?=App::config('url')?>operater/index"><i id="navbaricon" class="fa-solid fa-users"></i>Operaters</a></li>
            <?php elseif (App::oper()): ?>
                                    <li class="nav-item shadow btn btn-primary rounded rounded-3 bg-gradient mx-2"><a class="nav-link text-white" href="<?=App::config('url')?>users/index"><i id="navbaricon" class="fa-solid fa-users"></i>Users</a></li>
                                    <li class="nav-item shadow btn btn-primary rounded rounded-3 bg-gradient mx-2"><a class="nav-link text-white" href="<?=App::config('url')?>posts/index"><i id="navbaricon" class="fa-solid fa-note-sticky"></i>Posts</a></li>
                                    <li class="nav-item shadow btn btn-primary rounded rounded-3 bg-gradient mx-2"><a class="nav-link text-white" href="<?=App::config('url')?>comments/index"><i id="navbaricon" class="fa-solid fa-comment"></i>Comments</a></li>
            <?php else : ?>
                            <? // OVDJE ĆE IĆI SVE OD OBIČNO PRIJAVLJENIH KORISNIKA ... NAKON OVIH IF-OVA?>
                            <li class="nav-item shadow btn btn-primary rounded rounded-3 bg-gradient mx-2">
                              <a class="nav-link text-white" href="<?=App::config('url')?>"><i id="navbaricon" class="fa-solid fa-house"></i>Home</a>
                            </li>
                            <li class="nav-item dropdown shadow btn btn-primary rounded rounded-3 bg-gradient mx-2">
                              <a class="nav-link text-white" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              <i id="navbaricon" class="fa-solid fa-user"></i>Me
                              </a>
                              <ul class="dropdown-menu bg-transparent text-white border-0" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item shadow btn btn-primary bg-primary text-white rounded rounded-3 bg-gradient m-1 p-3" href="<?=App::config('url')?>user/myProfile"><i class="me-2 fa fa-user"></i> My profile</a></li>
                                <li><a class="dropdown-item shadow btn btn-primary bg-primary text-white rounded rounded-3 bg-gradient m-1 p-3" href="<?=App::config('url')?>user/editMyProfile/<?=$_SESSION['auth']->sifra?>"><i class="me-2 fa fa-pen"></i> Edit my profile</a></li>
                              </ul>
                            </li>
                            <li class="nav-item dropdown shadow btn btn-primary bg-gradient rounded rounded-3 mx-2">
                              <a class="nav-link text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              <i id="navbaricon" class="fa-solid fa-gear"></i>Settings
                              </a>
                              <ul class="dropdown-menu bg-transparent rounded rounded-3 mx-2 border-0" aria-labelledby="navbarDropdown">
                                <?php if($_SESSION['auth']->administrator): ?>
                                  <li><a class="dropdown-item shadow btn btn-primary bg-primary text-white rounded rounded-3 bg-gradient m-1 p-3" href="<?=App::config('url')?>report/spam"><i class="me-2 fa fa-bullhorn"></i> Report spam/abuse</a></li>
                                <?php else: ?>
                                  <li><a class="dropdown-item shadow btn btn-primary bg-primary text-white rounded rounded-3 bg-gradient m-1 p-3" href="<?=App::config('url')?>report/adminapplication"><i class="me-2 fa fa-star"></i> Apply for admin</a></li>
                                <?php endif; ?>
                                <li><a class="dropdown-item shadow btn btn-primary bg-primary text-white rounded rounded-3 bg-gradient m-1 p-3" href="<?=App::config('url')?>report/bug"><i class="me-2 fa fa-bug"></i> Report a bug</a></li>
                              </ul>
                            </li>
              <?php endif; ?>
                            <li class="nav-item shadow btn btn-primary rounded rounded-3 bg-gradient mx-2">
                                <a class="nav-link text-white" href="<?=App::config('url')?>index/logout"><i id="navbaricon" class="fa-solid fa-power-off"></i>Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <?php endif; ?>
<!--END NAVBAR-->