<script src="<?=App::config('url')?>public/js/fontawesome.js"></script>
<script src="<?=App::config('url')?>public/js/bootstrap.bundle.js"></script>
<script src="<?=App::config('url')?>public/js/jquery.js"></script>
<script src="<?=App::config('url')?>public/js/popper.js"></script>

<?php if(isset($jsdependency))
{
    foreach ($jsdependency as $p)
    {
        echo $p;
    }
}
?>

<?php if(isset($js)): ?>
    <script src="<?php echo App::config('url') . 'public/js/' . $js?>"></script>
<?php endif; ?>

<script src="<?=App::config('url')?>public/js/app.js"></script>